import './globals.css';
import type { Metadata } from 'next';
import Header from './Header';

export const metadata: Metadata = {
  title: 'poketter',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body className='container mx-auto px-4 sm:px-28 bg-custom-gray text-custom-white'>
        <div className='flex flex-col min-h-screen'>
          <Header />
          <main className='flex-grow'>{children}</main>
        </div>
      </body>
    </html>
  );
}
